### ISSUE TITLE
ReportParse.js async function() not working

### ISSUE THREAD

**Issue by r-arimura7** [tokyoevh/web-posted-pdf-text_Scraper#1]
@shinout ,

While main() successfully obtains ReportParse via module.exports on ReportParse.js, it only returns "[AsyncFunction: ReportParse]" in console. 

Instead, it should return below foreign exchange market commentary written in report posted at : 
http://www.am-one.co.jp/pdf/report/7377/200206_JSMarketDaily.pdf

【為替】
●東京時間では、1ドル=109円35銭近辺、1ユーロ=120円70銭近辺で終了。中国の経済対策への期待を背景に日米の株式市
場が上昇したことなどから、投資家のリスク回避姿勢が弱まり米ドル買いが優勢となった。もっとも、時間外取引で米長期金利
が低下し、日米金利差縮小の思惑から米ドル買いが弱まる場面もみられた。
●欧米時間では、1ドル=109円85銭近辺、1ユーロ=120円80銭近辺で終了。米国株式市場が上昇したことや米国金融当局者
が新型肺炎について米国経済に深刻な影響を及ぼさないとの認識を示したことなどから、米ドル買いが進んだ。

Any idea why this is not working?

**Comment by shinout** [comment]
https://github.com/tokyoevh/web-posted-pdf-text_Scraper/blob/bb7880bff09fbc51b0361bd448e3d16abda9849f/mktCommentScraper.js#L9

resultsは関数を定義しただけで、それ自体が実行されていないからです。

**Comment by shinout** [comment]
```js
const reportFileName = "test";
const ReportParse = require("./ReportParse");
const TestResults = require("./TestFile");
//const url = "http://www.am-one.co.jp/pdf/report/7377/200206_JSMarketDaily.pdf"; commented out for future inculusion of url argument in "results" function

const main = async () => {
  const results = await ReportParse();
};

main();
```

**Comment by r-arimura7** [comment]
ありがとうございます。

呼び出し元の関数が実行されていなかった旨承知しました。
尚、現状のところ、呼び出される関数ファイルのReportParse.jsの戻り値をうまく受け取れていないのが問題かと理解しています。

具体的には呼び出し元でReportParse()を実行して、戻り値をconosle.logするとundefinedと返されます。

一方で呼び出し先ReportParse()関数の処理は実行できており（下記// This line works）、.
おそらくmodule.exportsにReportParseの戻り値が入っていないのではないかと疑っています。

私も検証の方法を探っていますが
any idea?


```js

const fileSelect = require("fs");
const pdf = require("pdf-parse");
const crawler = require("crawler-request");
const ReportParse = async function() {
  await crawler(
    "http://www.am-one.co.jp/pdf/report/7377/200206_JSMarketDaily.pdf"
  ).then(response => {
    const comment = response.text;
    const headerTitle = comment.split("）");
    const datestring = headerTitle[0].split("（");
    const SplitComment = comment.split("【為替】");
    const FXcomment = SplitComment[1].split("【リート・商品】");
    console.log(FXcomment[0]); // This line works.
    return FXcomment[0];
  });
};

module.exports = ReportParse; 

```

**Comment by r-arimura7** [comment]
@shinout This issue has been resolved. Thanks for your help.
